## Matrix multiplication

In [2]:
import numpy as np
import torch

A multiplicação de matrizes é feito para:

MxN * NxP = MxP

**Using numpy**

In [9]:
# create some random matrices

A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications
#print(np.round(A@B, 2)), print(' ')
#print(np.round(A@C, 2)), print(' ')
#print(np.round(B@C, 2)), print(' ')
print(np.round(C.T@A, 2))

[[ 4.2   1.48 -2.19  1.12]
 [ 2.39  0.79 -2.06  0.31]
 [ 1.72  0.66 -1.57 -0.35]
 [-3.84 -1.47  3.2   0.52]
 [ 0.65  0.17 -0.15  0.62]
 [-0.54 -0.2   1.05  0.5 ]
 [-3.18 -1.17  1.39 -0.8 ]]


**Using pytorch**

In [12]:
# create some random matrices
A = torch.randn(3,4)
B = torch.randn(4,5)
C = torch.randn(3,7)

# try some multiplications...
#print(np.round(A@B, 2)), print(' ')
#print(np.round(A@C, 2)), print(' ')
#print(np.round(B@C, 2)), print(' ')
print(np.round(C.T@A, 2))

tensor([[-0.8800,  0.0700, -0.0100, -0.9200],
        [ 2.7600,  1.4600,  3.2900, -0.3700],
        [ 0.1000,  0.6400,  1.6800, -0.9600],
        [ 2.1200,  0.3400,  1.5200,  1.4600],
        [ 2.1900,  1.0200,  0.7900, -0.7100],
        [-3.0600,  0.3000,  3.4800, -1.8000],
        [-2.4200,  0.5100,  4.0000, -1.6300]])
