## Min/max and argmin/argmax

Como podemos encontrar pontos mínimos e máximos de um conjunto de números.

$$
min \{1,-1,3,0,4,3 \} = -1
\\
max \{1,-1,3,0,4,3 \} = 4
$$

para o argumento mínimo e máximo corresponde a posição do elemento mín/máx, notando que a posição inicial é 1.

$$
argmin \{1,-1,3,0,4,3 \} = 2
\\
argmax \{1,-1,3,0,4,3 \} = 5
$$

In [2]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

## Using numpy

In [ ]:
# create a vector
v = np.array([1,40,2,-3])

# find and report the maximum and minimum values
minval = np.min(v)
maxval = np.max(v)

print('min,max: %g,%g' %(minval,maxval))

# now for the argmin/max

minidx = np.argmin(v)
maxidx = np.argmax(v)
print('artg min,max: %g,%g' %(minidx,maxidx)), print(' ')
# note: the first positions is 0

# confirm
print(f'min val is {v[minidx]}, max val is {v[maxidx]}')

min,max: -3,40
artg min,max: 3,1
 
min val is -3, max val is 40


In [17]:
# repeat with matrix
M = np.array([[0,1,10],[20,8,5]])
print(M), print(' ')

# various minima in this matrix!
minvals1 = np.min(M) # minimum from ENTIRE matrix
minvals2 = np.min(M,axis=0) # min of each column (across rows)
minvals3 = np.min(M,axis=1) # min of each row (across columns)

print(minvals1)
print(minvals2)
print(minvals3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 1 5]
[0 5]


In [18]:
# various minima is this matrix!
minidx1 = np.argmin(M) # minimum from ENTIRE matrix
minidx2 = np.argmin(M,axis=0) # min of each column (across rows)
minidx3 = np.argmin(M,axis=1) # min of each row (across columns)

# print the out
print(M), print(' ')
print(minidx1)
print(minidx2)
print(minidx3)

[[ 0  1 10]
 [20  8  5]]
 
0
[0 0 1]
[0 2]


## Now using pytorch

In [30]:
# create a vector
v = torch.tensor([1,40,2,-3])

# find and report the maximum and minimum values

minval = torch.min(v)
maxval = torch.max(v)

print('min, max: %g,%g' %(minval,maxval))

# now for the arg min/max

minidx = torch.argmin(v)
maxidx = torch.argmax(v)

print('arg min,max: %g,%g' %(minidx,maxidx))

# compare
print(f'the minimum value {v[minidx]} and the maximum value {v[maxidx]}')

min, max: -3,40
arg min,max: 3,1
the minimum value -3 and the maximum value 40


In [44]:
# repeat the same sentence using matrix

M = torch.tensor([[0,1,10],[20,8,5]])
print(M),print(' ');

# various minima in this matrix
min1 = torch.min(M) # the geral minimum
min2 = torch.min(M,axis=0) # minimum of each column
min3 = torch.min(M,axis=1) # minimum of each row

# print them out
print(min1), print(' ')

print(min2)
print(min2.values)
print(min2.indices), print(' ')

print(min3)
print(min3.values)
print(min3.indices), print(' ');


tensor([[ 0,  1, 10],
        [20,  8,  5]])
 
tensor(0)
 
torch.return_types.min(
values=tensor([0, 1, 5]),
indices=tensor([0, 0, 1]))
tensor([0, 1, 5])
tensor([0, 0, 1])
 
torch.return_types.min(
values=tensor([0, 5]),
indices=tensor([0, 2]))
tensor([0, 5])
tensor([0, 2])
 
