## Reproducible randomness via seeding

Diferentes metodologias para semear (seeding) números aleatórios. Fazer isso torna o modelo reproduzível, usando inicializações aleatórias.

In [1]:
# import libraries
import numpy as np
import torch

In [23]:
# generate a few random numbers
np.random.randn(5)

array([-0.47463122, -1.16549511, -1.26619754,  0.37214943,  0.79340459])

In [75]:
# repeat after fixing the seed (old-but-still-widely-used method)
np.random.seed(17) # 17 é um número arbitrário, que indica o estado/posição da semeadura, nesse estado há minha semente aleatória

# a seed faz com que os valores aleatório gerados sejam os mesmos para diferentes iterações
print(np.random.randn(5))
print(np.random.randn(5))

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]


## New seed mechanism in numpy (recommended)

In [ ]:
randseed1 = np.random.RandomState(17)
randseed2 = np.random.RandomState(20210530) 

# o valor do RandomState() indica um posição em que os valores random foram salvos.

print(randseed1.randn(5)) # same sequence
print(randseed2.randn(5)) # different from above. but same each time
print(randseed1.randn(5)) # same as two up
print(randseed2.randn(5)) # same as two up
print(np.random.randn(5)) # different every time

[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[-0.24972681 -1.01951826  2.23461339  0.72764703  1.2921122 ]
[ 1.88663893 -0.11169829 -0.36210134  0.14867505 -0.43778315]
[ 1.15494929 -0.0015467  -0.11196868 -1.08136725  0.10265891]
[ 0.79840199 -0.61007005  1.18540421 -0.71083401 -0.78112893]


## Now in pytorch

In [89]:
torch.randn(5) # tensor with standard normal variance's elements

tensor([ 0.1534, -2.6631, -1.4311, -0.5483,  0.3232])

In [107]:
torch.manual_seed(17)
print(torch.randn(5))

# torch's seed doesn't spread to numpy
test = np.random.RandomState(17)
print(test.randn(5)) # fixado pelo seed

print(np.random.randn(5)) # random every time

tensor([-1.4135,  0.2336,  0.0340,  0.3499, -0.0145])
[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]
[ 0.13126776 -1.21256024  0.15999085 -0.75522304  0.34989599]
