## Functions

Compreender inputs and outputs, a sintaxe de funções em python

In [ ]:
# Uma função do python é a sum, que faz a soma de elementos, por exemplo de uma lista:

sum([10,20,30])

list = [20,20,20,7.0]
sum(list) # sum faz apenas soma de elementos int e float

# Note que a função possui o input, neste caso a lista, e um output, resultado da soma.

input  = list
output = sum(input)
print('The sum is '+ str(output))

The sum is 67.0


In [9]:
# Podemos criar as próprias funções, a partir de operações lógicas ou outros artifícios.

# Por exemplo, calcular a média da list

average = sum(list)/len(list)
print('The mean (average) of '+str(list)+' is '+str(average))

The mean (average) of [20, 20, 20, 7.0] is 16.75


## Python libraries (numpy)

Existem bibliotecas que fornecem funções já setadas, assim chamando a library é possível usar seus recursos.

In [55]:
# Podemos adicionar as bibliotecas ao projeto em ambiente virtual
# Abrimos o terminal
# python -m venv venv
# .venv\Scripts\Activate
# pip install "library"

# Para importar a biblioteca:

import numpy as np # em que a biblioteca é numpy e para chamarmos no nosso projeto usando uma abreviação: np

from numpy import mean as mn # dentro da biblioteca numpy podemos importar apenas uma função específica. Isso é interessante para não pesar o projeto.

# nesse caso, além de chamar a função, eu dou um apelido para ela

input = [10,20,30]

mn(input) # obtenho aqui a média dos elementos no input

output = np.average(input)
print("Exemple of output using numpy function (average): " + str(output))


Exemple of output using numpy function (average): 20.0


In [23]:
# Uma função que podemos usar:

x = np.linspace(1,7,5) # temos 5 números linearmente espaçados entre 1 e 7.
type(x) # O resultado é uma matriz numpy

numpy.ndarray

In [ ]:
input_np = np.array(input)

print(type(input)) # os dados originais são uma lista
print(type(input_np)) # quando usamos a função array convertemos para uma matriz numpy.


<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
# Há funções que podemos aplicar direto aos objetos

input_np.mean() # média
input_np.min()  # mínimo
input_np.max()  # input

# podemos aplicar as funções também:

x = np.max(input_np) # 'origem da função' . 'função' (objeto)
x = input_np.max() # objeto . 'função direta do np'

# Ambos os métodos usados geram o mesmo resultado e mesmo tipo de var.


numpy.int64

In [ ]:
# in-placa
# out-of-place / no-in-place operations

# Algumas operações no python alteram a variável chamando uma certo função. Por exemplo:

n = [4,3,5,2,6,1,7]
nn = np.array(n)

print(nn)
nn.sort() # a aplicação do método sort() altera o nn
print(nn) # variável nn está organizada


# (Esse é um exemplo de in-placa)

[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


In [ ]:
# Porém se realizarmos o mesmo processo, porém usando a função do numpy
n = [4,3,5,2,6,1,7]
nn = np.array(n)

print(nn)
np.sort(nn) # a aplicação do método do np.sort() não altera o nn
print(nn)   # variável nn não sofre alteração.

# Para isso ser efetivo, precisamos atribuir a mudança realizada pelo método à variável:

nn = np.sort(nn) # por exemplo
print(nn)

# (Esse é um exemplo de no-in-placa ou out-of-place)


[4 3 5 2 6 1 7]
[4 3 5 2 6 1 7]
[1 2 3 4 5 6 7]


## Python libraries (Pandas)

Pandas é uma biblioteca que permite manipular tabelas (matrizes, listas, dicionários)

In [28]:
import numpy as np
import pandas as pd
# os apelidos dados, np e pd, são módulos adicionados ao projeto.

# create random data
#np.random.randn(5,5) # criamos uma matriz 5x5 

var1 = np.random.randn(100)*5 + 20 # criamos uma matriz que apresenta 100 elementos distribuídos ao longo de 20 linhas e 5 colunas.

var2 = np.random.randn(100)>0 # podemos criar uma matriz que avalia cada elemento logicamente.

# variables labels
labels = ['Temp(C)', 'Ice cream']

# put them together into a dictionary
D = {labels[0]:var1, labels[1]:var2}

# import the dictionary into a pandas dataframe (df)

df = pd.DataFrame(data=D)
# O dataframe permite visualizar o conjunto de dados
D

{'Temp(C)': array([19.34594675, 15.30112333, 20.23973392, 20.73998811, 11.4438102 ,
        25.00983234, 17.50403824, 27.75305774, 27.03778138, 29.05725876,
        22.59556808, 22.22978209, 22.39046218, 14.98700444, 13.35335562,
        15.00882966, 22.91643055, 20.21153345, 22.56949731, 15.24270886,
        18.07219091, 22.02148511, 23.50691653, 16.52658174, 19.51125647,
        15.13856174, 22.69720248, 21.30306456, 13.49780741, 25.15923511,
        21.99379511, 10.00831584, 21.80401425, 21.19987006, 20.89018049,
        28.34519281, 21.60661867, 19.65846941, 12.12337034, 17.86856902,
        12.8864391 , 25.07550077, 18.07391815, 19.28934754, 21.81939231,
        18.35302136, 20.13868146, 21.27141298, 20.0720031 , 17.01321549,
        11.4834858 , 18.84258708, 19.08386499, 21.82566691, 21.334477  ,
        23.10634177, 17.13287613, 26.70063627, 21.41429633, 25.56710232,
        19.55465059, 16.41125069,  9.67271065, 19.68636122, 12.80907241,
        26.07832984, 23.54718761, 24.737

In [31]:
# Podemos visualizar partes dos dados:

df.head() # mostra os primeiros 5 dados

df.count() # mostra a quantidade de elementos para cada coluna, além do tipo de dados.

df.mean() # a média dos elementos no dicionário para cada coluna. Note que ele faz a média até de dados booleans, convertendo falsos em 0 e verdadeiros em 1.

Temp(C)      19.733199
Ice cream     0.510000
dtype: float64

In [45]:
# Exercise 
# Create a pandas dataframe with:
#  integers going from 0 to 10, their square, and their log.

nums = np.array(range(11))

df = pd.DataFrame({'nums':nums,'square':nums**2,'log':np.log(nums)})
df

# nesse resultado o warning

C:\Users\Igor Oliveira\AppData\Local\Temp\ipykernel_4072\3924042302.py:7: RuntimeWarning: divide by zero encountered in log
  df = pd.DataFrame({'nums':nums,'square':nums**2,'log':np.log(nums)})


,nums,square,log
0,0,0,-inf
1,1,1,0.000000
2,2,4,0.693147
3,3,9,1.098612
4,4,16,1.386294
5,5,25,1.609438
6,6,36,1.791759
7,7,49,1.945910
8,8,64,2.079442
9,9,81,2.197225


## Getting help on functions